### ISSUE TITLE
'PCB_PLOT_PARAMS' object has no attribute 'SetSvgPrecision' - Debian 11 Bullseye

### ISSUE THREAD

**Issue by ONLYA** [leoheck/kiri#49]
This error happens during the image generation stage on Debian 11 Bullseye (latest version of Debian).
```
AttributeError: 'PCB_PLOT_PARAMS' object has no attribute 'SetSvgPrecision'
```

It will make the PCB image not shown and only the schematic changes are displayed.

It is because Debian 11 only has KiCad 5.0.9 as the stable release and the `pcbnew` python port of KiCad 5.0.9 does not have `SetSvgPrecision` method as I have checked by calling `import _pcbnew;_pcbnew.PCB_PLOT_PARAMS_SetSvgPrecision`. In order to make it work, KiCad 6+ should be installed. On Debian 11, this is done by adding "bullseye-backports" apt repo and install KiCad from it. 

It is noted that the other platforms like Ubuntu 20.04 may also encounter this problem.

**Comment by leoheck** [comment]
Did you try to move the canvas on the HTML? Sometimes it plots but the image are hidden in the Righ-Bottom. I have a tweak svg script to fix that. But I might have removed it after Kicad >= 6.0.3 since this was working and I forgot about Kicad 5.*

Please, check if Kira calls this [plotgitsch_svg_tweaks](https://github.com/leoheck/kiri/blob/main/bin/plotgitsch_svg_tweaks) somewhere. If not, let me know, and i will check if I can put it back for Kicad 5.*
And if you try to use this script, let me know if it fixed/improved the issue for you.

Kicad files are tricky to work with. But I appreciate your efforts to help me.

**Comment by ONLYA** [comment]
I did not move anything in the HTML. The PCB svg's were not generated at all.
And it seems that `plotgitsch_svg_tweaks` is used to generate only the schematics' svg but not the PCBs'. 
I removed KiCad 6 and reinstalled the KiCad 5. `plotgitsch_svg_tweaks` was not called. However, the schematic svg's were generated but the PCB ones were not.

_I think this problem is not about your scripts but for the `kidiff` or the KiCad-Diff, which called the undefined methods in KiCad v5 Python API._

In my opinion, there could be two ways to solve this: 
- Modify the [`install_dependencies.sh`](https://github.com/leoheck/kiri/blob/main/install_dependencies.sh) to install KiCad v6+ for all platforms.
- Create a workaround file to generate the svg along with the KiCad-Diff. (while some modifications to kidiff may needed).

**Comment by ONLYA** [comment]
You can see the log of this here: https://github.com/ONLYA/Display_only/blob/master/8/kiri-kicad-v5.log

**Comment by leoheck** [comment]
> I think this problem is not about your scripts but for the kidiff or the KiCad-Diff, which called the undefined methods in KiCad v5 Python API.

Oh, yeah, I misunderstood.

Yeah, but in this case, I can change Kicad-Diff to skip this item, and it will generate svgs with some issues, that may work on some svg viewers but not on most common browsers like Chrome, Safari, and maybe only on Firefox too. Then a tweak on the generated svg files maybe the needed to fix something (I remember I had something like that, we just have to check git history). I think I had a script that fixes those generated files but it is a bit time-consuming. Not much, but it adds about 1s for each commit. 

So, right now you have Kicad 5.* because you said Debian does not make available Kicad.6, right? Don't you think people will try to install Kicad 6 from a PPA or another place, maybe from AppImage? 

I will check if I can replicate your system to check. Which version of Debian do you have?

**Comment by ONLYA** [comment]
KiCad 6 is only available as a testing package. So you need to manually add the bullseye-backports in the `/etc/apt/sources.list`. And then do a `sudo apt update;sudo apt install kicad/bullseye-backports`.
I am using the latest stable version of Debian, which is Debian 11. You can create a virtual env with the downloaded iso images.

**Comment by leoheck** [comment]
I see, is it not a normal practice? I mean... the ones that want to use it will do it, right?

**Comment by ONLYA** [comment]
Yep, but the solution to this problem is hard to find. It took me about 30 minutes to find out the cause. (I was stupid enough to try to build KiCad 6 from source and stuck in wxWidgets build🤦‍♂️)

So it could save the time to do the tweaks in the scripts for direct production instead of finding solutions.

**Comment by leoheck** [comment]
I would say you were brave enough to try that. I still have to check if I can improve this, because sometime in the past I just tough that people would use Kicad 6, but since I was wrong, then I will check how to make this better.

**Comment by ONLYA** [comment]
> I would say you were brave enough to try that. I still have to check if I can improve this, because sometime in the past I just tough that people would use Kicad 6, but since I was wrong, then I will check how to make this better.

People use KiCad 6 for daily uses but it may not be v6 any more when other environments involved.

> did you try to comment out the `SetSvgPrecision` line on Kidiff? Does it work? Does it at least generate files?

I have not tried that. I think it should work. A `try... except...` block will work for v5 and v6 cases. 

I now do not have the environment I used before but will try it tomorrow.

**Comment by leoheck** [comment]
Sure, whenever you have time. Let's work together to make it useful on your
system. This was my first time installing debian and the installation
process is annoying haha. It asks me a bunch of questions.  Invite you to
use Ubuntu instead, to get the job done haha. Maybe installing it on WLS is
easier since it may not ask those annoying questions.

**Comment by leoheck** [comment]
Hey, I could install your Debian 11 and the Kicad `5.1.9` (not the Kicad 5.0.9 as you said in the first pots, that was a mistake I think). Everything was installed smoothly, maybe because we fixed the install_dependencies before. 

I could see the issue you were talking about. Yeh, none of the .svg files were being created. Then I upgraded the module removing the missing function for Kicad 5.* and also for Kicad < 6.0.3 since they may have this bug too. 

Now it seems to be working. You can upgrade your repo to the upgrade Kicad-diff submodule. Or you can run the Kiri script once more to upgrade it. 

Let me know if this fixes this problem. Please, feel free to open this issue again if the problem persists.

**Comment by ONLYA** [comment]
> Hey, I could install your Debian 11 and the Kicad `5.1.9` (not the Kicad 5.0.9 as you said in the first pots, that was a mistake I think). Everything was installed smoothly, maybe because we fixed the install_dependencies before.
> 
> I could see the issue you were talking about. Yeh, none of the .svg files were being created. Then I upgraded the module removing the missing function for Kicad 5.* and also for Kicad < 6.0.3 since they may have this bug too.
> 
> Now it seems to be working. You can upgrade your repo to the upgrade Kicad-diff submodule. Or you can run the Kiri script once more to upgrade it.
> 
> Let me know if this fixes this problem. Please, feel free to open this issue again if the problem persists.

Great. The new modifications worked fine for KiCad 5.*. Thanks for the update!
