### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by AndrewKeene** [leoheck/kiri#57]
I'm not positive that this is an ARM64 issue related to the Apple M1, however I'm having some issues installing the dependencies for Kiri on a 14" M1 MBP.  Any known workaround for this following console output?  Thanks.

```bash
Switch invariant: ["ocaml-base-compiler" {= "4.09.1"} | "ocaml-system" {= "4.09.1"}]
[ERROR] Could not determine which packages to install for this switch:
  * Missing dependency:
    - ocaml-base-compiler = 4.09.1 | ocaml-system = 4.09.1
    unmet availability conditions: '!(os = "macos" & arch = "arm64")'
    unmet availability conditions: 'sys-ocaml-version = "4.09.1"'

**Comment by leoheck** [comment]
Oh, nice to hear you are trying to run it on M1. 

Installing this `OCaml/Opam/plotgitsch/kicadsh` thing is quite complicated, every time.

If you are going to use Kiri for Kicad 6 files, then this Ocaml thing is not important since it won't be used. 
In this case, the simple solution would be to remove this step completely. 

You will need to remove lines 259 and 260 on `install_dependencies` script

![image](https://user-images.githubusercontent.com/1277920/188628982-4d0b5005-509f-40c0-87e2-9f3cb694839a.png)

And also, remove line 118 in the `install_kiri` script.

![image](https://user-images.githubusercontent.com/1277920/188629190-635b53ac-737a-4137-a3b6-2577315ba050.png)

Now, if you are going to use Kicad 5, then it would be good to install `OCaml/Opam`. You could try to find out how to install Opam and its dependencies on M1. I don't have one M1 with me right now, but I will check once I put my hands on one. Meanwhile, you can keep interacting with me here so we could try to find a solution for this.

**Comment by leoheck** [comment]
This recent answer here suggest that some things are not available yet for ARM MacOS yet. 
https://github.com/ocaml/opam-repository/issues/21355

> Only ocaml versions 4.10.2 and > 4.12 support macos with arm64

Then he suggests using a specific version of OCaml

Then, in this way, you could try to change the version of the installer
You could try this.

```bash
init_opam()
{
	# Plotgitsch dependencies
	# if [[ ! -d "$HOME/.opam/4.09.1" ]]; then  # <<<<<<<<<<<<<<< REMOVED
	if [[ ! -d "$HOME/.opam/4.10.2" ]]; then  # <<<<<<<<<<<<<<< ADDED
		opam init --disable-sandboxing --reinit
		# opam switch create 4.09.1  # <<<<<<<<<<<<<<< REMOVED
	        opam switch create 4.10.2    # <<<<<<<<<<<<<<< ADDED
	fi
	opam switch 4.09.1
	eval "$(opam env)"
}

install_opam_modules()
{
	# Update packages knowledge
	opam update

	# Plotgitsch dependencies
	opam install -y digestif
	opam install -y lwt
	opam install -y lwt_ppx
	opam install -y cmdliner
	opam install -y base64
	opam install -y sha
	opam install -y tyxml
	opam install -y git-unix
}
```

Just copy and paste the previous code in the console, and then type:
```
init_opam
install_opam_modules
```

**Comment by AndrewKeene** [comment]
Leandro, 

Your fix above with 4.10.2 worked for ARM64.   Outside if the if block I then changed to:
`
opam switch 4.10.2
`
Thank you for the help.

**Comment by leoheck** [comment]
If this fixes, I will consider upgrade opam to the default install, thanks for the feedback!

**Comment by TIGER9PO** [comment]
This will be helpful
